name: Build and Test - NodeJS

on:
  workflow_call:
    inputs:
      enable_coverage:
        description: 'A boolean value indicating if coverage reporting shall be enabled. If provided the secret token is required.'
        default: false
        required: false
        type: boolean
    secrets:
      token:
        description: 'The GitHub Token which is used to push to Coveralls'
        required: false

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        node_version: [18]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: install
        run: npm ci
        env:
          CI: true
      - name: build
        run: npm run build --if-present
        env:
          CI: true