name: Discord Webhooks

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      color:
        required: false
        type: string
      username:
        required: false
        type: string
      avatar_url:
        required: false
        type: string
      footer_title:
        required: true
        type: string
      pre_release_footer_title:
        required: false
        type: string
      footer_icon_url:
        required: false
        type: string
      footer_timestamp:
        required: false
        type: string
    secrets:
      DISCORD_WEBHOOK_URL_LATEST:
        required: false
      DISCORD_WEBHOOK_URL_BETA:
        required: false

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    name: GitHub Releases to Discord
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Latest Release
        if: ${{ github.event.release.prerelease == false }}
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL_LATEST }}
          color: ${{ inputs.color || '490899'}}
          username: ${{ inputs.username || 'Bubba8291'}}
          avatar_url: ${{ inputs.avatar_url || 'https://raw.githubusercontent.com/homebridge/branding/latest/logos/homebridge-color-round-stylized.png'}}
          footer_title: ${{ inputs.footer_title }}
          footer_icon_url: ${{ inputs.footer_icon_url || 'https://raw.githubusercontent.com/homebridge/branding/latest/logos/homebridge-color-round-stylized.png'}}
          footer_timestamp: ${{ inputs.footer_timestamp || true }}
    
      - name: Pre-Release
        if: ${{ github.event.release.prerelease == true }}
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL_BETA }}
          color: ${{ inputs.color || '490899'}}
          username: ${{ inputs.username || 'Bubba8291'}}
          avatar_url: ${{ inputs.avatar_url || 'https://raw.githubusercontent.com/homebridge/branding/latest/logos/homebridge-color-round-stylized.png'}}
          footer_title: "Pre-Release: ${{ inputs.pre_release_footer_title || inputs.footer_title }}"
          footer_icon_url: ${{ inputs.footer_icon_url || 'https://raw.githubusercontent.com/homebridge/branding/latest/logos/homebridge-color-round-stylized.png'}}
          footer_timestamp: ${{ inputs.footer_timestamp || true }}