name: Node Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_and_test:
    uses: ./.github/workflows/nodejs-build-and-test.yml
    with:
      enable_coverage: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: build_and_test

    if: ${{ github.repository == 'Bubba8291/homebridge-sharkiq' }}

    uses: ./.github/workflows/npm-publish.yml
    secrets:
      npm_auth_token: ${{ secrets.npm_token }}

  github-releases-to-discord:
    needs: publish

    if: ${{ github.repository == 'Bubba8291/homebridge-sharkiq' }}

    uses: ./.github/workflows/discord-webhooks.yml
    with:
      title: "SharkIQ"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}